#:kivy 2.0.0

<HomePage>:
    ScrollView:
        # id: prediction_text
        # do_scroll_x: False
        # do_scroll_y: True
        # width: root.width
        # height: root.height // 2.5

        # Label:
        #     id: prediction_t
        #     size_hint_y: None
        #     height: 200
        #     width: 500
        #     text_size: self.width, None
        #     padding: [10, 10]
        #     text: "Prediction" *100
        #     font_size: 24
        #     bold: True